version: '3'
services:
  server:
    container_name: IoTGateway-cont
    restart: always # 跟系統服務一起重啟
    network_mode: host # 網路: 使用實體機
    # 編譯時的設置
    build: 
      context: .
      dockerfile: Dockerfile.env
    
